version: "3"
volumes:
  prometheus_data: {}
  
services:

  eureka-server:
    build: ../eureka-server/
    ports:
      - "8761:8761"
    networks:
      - test-network


  product-stock:
    build: ../product-stock/
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://techefx-eureka-namng-service:8761/eureka
        -DZIPKIN_SERVER=http://zipkin:9411/
    ports:
      - "8800:8800"
    #    links:
    #      - zipkin
    depends_on:
      - eureka-server
    #      - zipkin
    networks:
      - test-network


  product-enquiry:
    build: ../product-enquiry/
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://techefx-eureka-namng-service:8761/eureka
        -DZIPKIN_SERVER=http://zipkin:9411/
    ports:
      - "8700:8700"
    #   links:
    #     - zipkin
    depends_on:
      - product-stock
    #     - zipkin
    networks:
      - test-network


  spring-cloud-api:
    build: ../spring-cloud-api/
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://techefx-eureka-namng-service:8761/eureka
        -DZIPKIN_SERVER=http://zipkin:9411/
 #       -DENQUIRY_SERVICE=http://techefx-product-enquiry-service:9700/
    ports:
      - "8900:8900"
    #   links:
    #     - zipkin
    depends_on:
      - eureka-server
      - product-enquiry
      - product-stock
    #      - zipkin
    networks:
      - test-network


  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/:/etc/prometheus
      - ./data/prometheus:/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=31d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    depends_on:
      - product-stock
    networks:
      - test-network


  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - test-network


  zipkin:
    image: openzipkin/zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"
    depends_on:
      - eureka-server
    networks:
      - test-network



networks:
  test-network:

